### ISSUE TITLE
Longer strings go out of bounds

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#107]
For https://github.com/phetsims/QA/issues/634. Not in published. Found while looking at https://github.com/phetsims/number-line-integers/issues/90, but as this affects non-movable checkboxes I think it should be addressed.
When strings are longer than normal (such as with `?stringTest=double` they will go out of bounds and off screen if the screen is close enough to the dev bounds.
![Image from iOS](https://user-images.githubusercontent.com/41024075/113455599-50024380-93c8-11eb-913c-1b09a8a28066.png)
<img width="895" alt="moreoutbound" src="https://user-images.githubusercontent.com/41024075/113455601-509ada00-93c8-11eb-8390-672f8a694898.png">
<img width="956" alt="newoutofbounds" src="https://user-images.githubusercontent.com/41024075/113455603-51337080-93c8-11eb-8c60-9521171f660a.png">

**Comment by jbphet** [comment]
I have fixed this in master and propagated the changes to the 1.1 branch.  I'll leave it open and will have QA verify the fix on the next RC.

**Comment by DevonQui** [comment]
Checked this on my iPad and Mac and it looked fixed. Closing
