### ISSUE TITLE
Add Africa, Asia and Latin America Character Sets

### ISSUE THREAD

**Issue by marlitas** [phetsims/number-line-integers#110]
The sim will need a preferences dialog and the full structure for character sets.

**Comment by marlitas** [comment]
The structure has been added in and USA character sets were created. Next steps need pngs of the Africa, Asia, and Latin America artwork as well as some feedback from @amanda-phet on what the icons in the combo box should be.

**Comment by marlitas** [comment]
I got confused on my issues. NLI got pngs and is ready to go.

**Comment by marlitas** [comment]
@amanda-phet. The usa and Africa character sets are now in if you want to take a look at them on your end.

**Comment by marlitas** [comment]
This has been added in and reviewed by @amanda-phet. Closing.

**Comment by amanda-phet** [comment]
Adding Oceania!

**Comment by marlitas** [comment]
Oceania is in. Over to @amanda-phet for review.

**Comment by amanda-phet** [comment]
All of the characters look great! Closing.
