### ISSUE TITLE
Oceania Characters in dropdown and Explore screen icon are different

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-integers#112]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Safari 17

**Problem description**
For https://github.com/phetsims/qa/issues/1002, for the Oceania character set, the dropdown character and the one in the Explore screen icon are different. Was this intentional?

Noting that it was intentional for the Explore screen icon to be the same for Africa and Africa Modest (from @marlitas over slack). 

**Visuals**
<img width="298" alt="Screenshot 2023-11-13 at 1 10 54 PM" src="https://github.com/phetsims/number-line-integers/assets/87318828/eaa088e6-fa54-458c-8020-e91e10732e8d">
<img width="227" alt="Screenshot 2023-11-13 at 1 10 40 PM" src="https://github.com/phetsims/number-line-integers/assets/87318828/e8baaa40-f3af-4ad4-ac5c-c3189c4b6b4c">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.2.0-dev.5/phet/number-line-integers_all_phet.html
Version: 1.2.0-dev.5 2023-11-13 16:44:44 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15
Language: en-US
Window: 1316x662
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
The character in the sim matches the one in the dropdown menu.

**Comment by KatieWoe** [comment]
I also noticed that the Explore screen icon for the Africa set is the Africa Modest character, rather than the Africa character.
![africa](https://github.com/phetsims/number-line-integers/assets/41024075/815ef56f-ea4a-4538-9ab8-149c12725372)

**Comment by amanda-phet** [comment]
Sorry for not announcing it, but those two screen icons will be updated before the next round of testing.

**Comment by amanda-phet** [comment]
Here are the updated screen icons. 

![exploreScreenNav-modest](https://github.com/phetsims/number-line-integers/assets/7852916/9754a561-83da-475b-a478-cd30e743d403)
![exploreScreenHome-modest](https://github.com/phetsims/number-line-integers/assets/7852916/65f8bb84-bc05-409e-ba79-b2ae7b9ab761)
![exploreScreenNav-Oceania](https://github.com/phetsims/number-line-integers/assets/7852916/c5dc4d7f-846c-4993-97a8-568a87678dff)
![exploreScreenHome-Oceania](https://github.com/phetsims/number-line-integers/assets/7852916/b093c445-260f-456f-91fc-64ca7fce5a8e)
![exploreScreenNav-Africa](https://github.com/phetsims/number-line-integers/assets/7852916/004b4a37-50b3-4156-91c8-2e7a2e3630d1)
![exploreScreenHome-Africa](https://github.com/phetsims/number-line-integers/assets/7852916/fe3743c8-1fc3-4985-94bd-f0c323f57a4b)

**Comment by marlitas** [comment]
This is updated in the above commit! Over to @amanda-phet  and @Nancy-Salpepi to check on main.

**Comment by KatieWoe** [comment]
Looks ok on main to me

**Comment by Nancy-Salpepi** [comment]
Everything looks correct on main to me!

**Comment by amanda-phet** [comment]
Looks great. Over to @marlitas to note in the next round of testing, or close.

**Comment by marlitas** [comment]
I think this is ready to close!
