### ISSUE TITLE
Values don't match after pressing Restart 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-integers#114]
**Test device**
MacBook Air M1 chip and Dell

**Operating System**
14.0 and Win10

**Browser**
Safari 17 and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1002, pressing the Restart button in the Elevation scene on the Explore screen will cause the absolute values to no longer match the actual values. 

**Steps to reproduce**
1. In the Elevation scene, check Absolute Value
2. Add the character, bird and fish to the scene
3. Press Restart
4. Add the character, bird and fish to the scene

**Visuals**
<img width="993" alt="Screenshot 2023-11-14 at 8 18 28 AM" src="https://github.com/phetsims/number-line-integers/assets/87318828/301b322e-5ca8-4983-bd0f-a849e0910060">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.2.0-dev.5/phet/number-line-integers_all_phet.html
Version: 1.2.0-dev.5 2023-11-13 16:44:44 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language: en-US
Window: 1386x728
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by KatieWoe** [comment]
Also happens with the reset scene button or even just adding a character, taking them off the scene, then adding them back in.

**Comment by marlitas** [comment]
I believe this is fixed above, but I would like to check in with @jbphet about it before closing. It relies on an assumption that a `PointController`'s `numberLinePoints` never has more than one active `numberLinePoint` at a time. In some testing it seems like that's accurate, but I'm not convinced since the type of that property is an `ObservableArray`. 

@Nancy-Salpepi or @KatieWoe, I think it's ready for you to check it on main but please leave open until I have a chance to meet with JB about it.

**Comment by Nancy-Salpepi** [comment]
@marlitas the text isn't correct this morning:
<img width="763" alt="Screenshot 2023-11-15 at 9 13 27 AM" src="https://github.com/phetsims/number-line-integers/assets/87318828/8c0caf00-5253-4332-84b2-17f92041e681">

**Comment by marlitas** [comment]
Oh boy... How did that happen? I tested it last night... I'm mostly away today, but I'll be able to check on it this afternoon.

**Comment by marlitas** [comment]
Okay... let's try this again. To confirm, this is what I'm seeing:

<img width="600" alt="image" src="https://github.com/phetsims/number-line-integers/assets/42476338/51e62e63-23ab-4974-a160-cb751f82dd35">

@Nancy-Salpepi can you check it on main?

**Comment by Nancy-Salpepi** [comment]
This looks fixed now on main @marlitas! 🙂

**Comment by marlitas** [comment]
While we met @jbphet I noticed that I no longer needed to wait until the multi-link to create the absolute value text. The most recent commit refactors the code to not have to use that awkward work-around. Ready to go for your review. Thanks!

**Comment by jbphet** [comment]
@marlitas - The changes mostly look fine.  I made some edits of my own, so I'm passing it back to you for final review and possible closure.

**Comment by marlitas** [comment]
@jbphet those are great edits. Thanks so much for cleaning that up. I believe this is ready to close!
