### ISSUE TITLE
negative sign appears in absolute value statement

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-integers#115]
**Test device**
MacBook Air M1 chip and Dell

**Operating System**
macOS 14.0 and Win10

**Browser**
Safari 17 and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1002, the negative sign still appears for the absolute value in the Elevation Scene

**Steps to reproduce**
1. In the Elevation Scene, check Absolute Value
2. Add character, fish and bird to the water (so the actual value is negative) --the absolute value should be positive

**Visuals**
Dev version:
<img width="993" alt="Screenshot 2023-11-14 at 8 31 43 AM" src="https://github.com/phetsims/number-line-integers/assets/87318828/da250da5-1b1d-4b91-965f-940855bcc22f">

Published: 
<img width="993" alt="Screenshot 2023-11-14 at 8 44 07 AM" src="https://github.com/phetsims/number-line-integers/assets/87318828/116789db-3cd8-4944-99bf-2cb7fa6c8a87">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.2.0-dev.5/phet/number-line-integers_all_phet.html
Version: 1.2.0-dev.5 2023-11-13 16:44:44 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language: en-US
Window: 1386x728
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by marlitas** [comment]
This should now be solved with the above commit. @Nancy-Salpepi can you confirm it looks good on main?

**Comment by Nancy-Salpepi** [comment]
This looks fixed now on main, but not sure if I should close because of https://github.com/phetsims/number-line-integers/issues/114.

**Comment by marlitas** [comment]
I think this is separate from #114 Thanks for checking in on that though. Closing :-)
