### ISSUE TITLE
'Opposite' Control not working correctly

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-integers#116]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Safari 17 and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1002, on the Generic Screen, the Opposite control isn't showing the values properly. Either both values will be positive if the Sphere is on the positive side OR both values will be negative if the sphere is on the negative side.

**Steps to reproduce**
1. On the generic screen, check Opposite --the value for the blue sphere is 1 and its opposite will also say 1
2. Add another sphere to the negative side --its value will be negative and its opposite will also be negative

**Visuals**
Dev version:

<img width="734" alt="Screenshot 2023-11-14 at 8 59 26 AM" src="https://github.com/phetsims/number-line-integers/assets/87318828/ce28cc5f-5a01-4dc1-b485-2cd60f2bddd9">

Published:

<img width="734" alt="Screenshot 2023-11-14 at 9 00 04 AM" src="https://github.com/phetsims/number-line-integers/assets/87318828/bcf04b2b-4cd0-45eb-bd8a-9902daaf4917">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.2.0-dev.5/phet/number-line-integers_all_phet.html
Version: 1.2.0-dev.5 2023-11-13 16:44:44 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language: en-US
Window: 1386x728
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by marlitas** [comment]
This was addressed in the above commit. @Nancy-Salpepi can you check all looks good on main?

**Comment by Nancy-Salpepi** [comment]
Looks good on main! Closing.
