### ISSUE TITLE
Absolute value statement layout wonky in Elevation scene

### ISSUE THREAD

**Issue by marlitas** [phetsims/number-line-integers#117]
While working on https://github.com/phetsims/number-line-integers/issues/115 I noticed the layout of the absoluteValue label looked wonky in the elevation scene. The label was not adjusting it's width dynamically, and it was slightly overlapping the swimming character.

**Comment by marlitas** [comment]
I think this is fixed now. Over to @amanda-phet to double check that the absolute value labels are looking good in the Explore Screen, elevation scene.

**Comment by amanda-phet** [comment]
Something is definitely not right... 
<img width="354" alt="image" src="https://github.com/phetsims/number-line-integers/assets/7852916/faad6903-4b1c-488e-b66a-5c1ed850c9a0">

**Comment by marlitas** [comment]
Haha yeah... I don't know what happened there. Fixed in https://github.com/phetsims/number-line-integers/issues/114, should be ready to check now.

**Comment by amanda-phet** [comment]
These look good to me! I like the rounded corners, much more current with how we do these labels now. The only thing I see is that I'd like a little more transparency/less opacity. It doesn't need to match the old one, but just go down .1 or .2. Super minor. (ex if they are currently .95 go down to .93)

<img width="267" alt="image" src="https://github.com/phetsims/number-line-integers/assets/7852916/dcdaac44-d352-4363-9b1a-eeaea00197c3">

<img width="277" alt="image" src="https://github.com/phetsims/number-line-integers/assets/7852916/2d454169-d479-4692-9438-6a8a8b31a1e8">

**Comment by marlitas** [comment]
Here it is we the new opacity:
<img width="724" alt="image" src="https://github.com/phetsims/number-line-integers/assets/42476338/269d4ebd-0d60-4115-a188-c66bcc52f6da">

If that looks good, feel free to close!

**Comment by amanda-phet** [comment]
Looks good, thanks!
