### ISSUE TITLE
Should we have a month selector for the temperature data?

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-integers#12]
@kathy-phet said this in an email:

> We've discussed during design this idea of being able to have a drop down - so you can change the month that is displayed of the temperature - setting to your local month at that time or your summer to make more personalized and local. 
>
> I just want to bring this up again now - so that its on the table and the data is downloaded and added in with this in mind. Unless there is a decision to not have this functionality. 

We're at the point where we should probably decide if we want to do this so that it can be rolled into the implementation.

**Comment by arnabp** [comment]
This was discussed in the status meeting on 7/25 and it was decided that we would move forward with the month selector. It was added into the sim in commits 57935f668e6a8fa02f51d4246fab52d15571430b, 8cad5f466b24fd6770db5929e49f0b630dbbadf9, d31bc23b6ab5dd010b49e56278ccaae22d808630, d573f90ba69caead3bc878bf319292d9f13f5934, 0786b4afee2a2484571dc6100bfc686f66d9b7dd, c11c3fb2151bc1028d8148dc0021205c326748de, and 1543bcdb91e523c46d5ad88663a6a9e49bb9f3ce
