### ISSUE TITLE
Temperature thermometer color contrast seems poor

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-line-integers#120]
From https://github.com/phetsims/number-line-integers/issues/119, I think orange and yellow are quite hard to see the difference between (on the number line to the left):

<img width="907" alt="image" src="https://github.com/phetsims/number-line-integers/assets/6856943/1e7fddb1-699c-42c9-89c7-64fcc96025d5">

**Comment by amanda-phet** [comment]
Yes, those aren't super easy to distinguish. However, the gradient (from very dark blue to very dark red) needs to cover a large range of values, so any values that are close together are necessarily going to have similar hues. This is the case across the entire gradient. So, I'm going to close this as won't fix.
