### ISSUE TITLE
update Latin American character

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-integers#122]
For https://github.com/phetsims/qa/issues/1010

In Number Line: Distance, @amanda-phet updated the Latin American character so that the screen icon and the one used in the sim matched (the paper airplane was flying in 2 different directions). 

Could the updated character be added to this sim as well?

NL: Distance
<img width="400" alt="Screenshot 2023-12-05 at 9 49 52 AM" src="https://github.com/phetsims/number-line-integers/assets/87318828/cebcf121-3630-4fb4-ae26-608cfc59ccea">

NL: Integers
<img width="305" alt="Screenshot 2023-12-05 at 9 52 21 AM" src="https://github.com/phetsims/number-line-integers/assets/87318828/fa734835-3164-4298-b431-74e816f9d354">

<img width="158" alt="Screenshot 2023-12-05 at 9 51 11 AM" src="https://github.com/phetsims/number-line-integers/assets/87318828/b630c102-04e9-427e-b23a-a0633a9fbf55">

**Comment by amanda-phet** [comment]
@marlitas if it's ok to make this change I can upload a new image.

**Comment by marlitas** [comment]
Yeah! Totally good. Let me know when it's uploaded in and I'll make sure it's all rendering correctly.

**Comment by amanda-phet** [comment]
New artwork is uploaded!

**Comment by marlitas** [comment]
Completed in the above commit. Closing!

**Comment by marlitas** [comment]
I forgot I need to cherry-pick this. Re-opening.

**Comment by marlitas** [comment]
I'm not sure why this issue is showing up in the NLD RC QA issue, but it has nothing to do with that RC. There are no cherry-picks needed for this issue closing again. Sorry for the flip-flopping.
