### ISSUE TITLE
Value on bank doesn't change

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-integers#123]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1010, on the Explore screen, in the Bank scene, the value on the bottom bank doesn't change as it is moved along the number line. The absolute value statement also indicates no value. 
The value on the top bank changes. 

**Steps to reproduce**
1. Go to the Bank scene on the Explore screen, drag the bank along the number line. 

**Visuals**
<img width="724" alt="Screenshot 2023-12-05 at 1 52 43 PM" src="https://github.com/phetsims/number-line-integers/assets/87318828/f849afdf-0702-4a34-aec1-a71bed96cfc6">

<img width="254" alt="Screenshot 2023-12-05 at 1 57 57 PM" src="https://github.com/phetsims/number-line-integers/assets/87318828/69fac5a4-8dec-434e-b363-4ed064d59bb4">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.2.0-dev.8/phet/number-line-integers_all_phet.html
Version: 1.2.0-dev.8 2023-12-02 00:33:09 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15
Language: en-US
Window: 1403x710
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by KatieWoe** [comment]
Here is what the absolute value label looks like in the negative.
![whatlook](https://github.com/phetsims/number-line-integers/assets/41024075/44a46e3b-426a-4916-9a27-86dc0b138325)

**Comment by marlitas** [comment]
This should now be fixed above. Over to @Nancy-Salpepi or @KatieWoe to check on main. Feel free to close if all looks well.

**Comment by KatieWoe** [comment]
Looks ok to me
