### ISSUE TITLE
Bank sizes are different

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-integers#125]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1016 in the Bank scene on the Explore screen was it intentional for the banks to be different sizes when they have the same value? 

**Visuals**
<img width="177" alt="Screenshot 2023-12-18 at 1 28 40 PM" src="https://github.com/phetsims/number-line-integers/assets/87318828/b5e285d7-1ee9-473f-8bcb-414dd24a1232">
<img width="125" alt="Screenshot 2023-12-18 at 1 37 42 PM" src="https://github.com/phetsims/number-line-integers/assets/87318828/2a80630e-fb24-4610-9ff5-92a24d9706cd">

**Comment by marlitas** [comment]
No, that is not intentional... not sure how that's happening. Marking as a bug.

**Comment by marlitas** [comment]
Addressed and ready for cherry pick

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.4. 
Closing.
