### ISSUE TITLE
xhtml file doesn't open

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-integers#126]
For https://github.com/phetsims/qa/issues/1016 I see the same errors as I did in https://github.com/phetsims/chipper/issues/1413 when trying to open the xhtml file:

<img width="510" alt="Screenshot 2023-12-18 at 4 02 18 PM" src="https://github.com/phetsims/number-line-integers/assets/87318828/01f556d8-9d02-4cab-a262-61f57aad5191">

**Comment by marlitas** [comment]
This fix is now being tracked in chipper https://github.com/phetsims/chipper/issues/1413, closing as a duplicate.
