### ISSUE TITLE
currency no longer centered on coin

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-integers#127]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1016, when the currency is longer than 1-2 characters, it is no longer centered. On published it is centered. 

**Visuals**
Ex: Turkman:
RC:
<img width="409" alt="Screenshot 2023-12-19 at 12 47 10 PM" src="https://github.com/phetsims/number-line-integers/assets/87318828/03b01e20-0634-40d9-91a5-b34429fb8626">

Published:

<img width="688" alt="Screenshot 2023-12-19 at 12 48 58 PM" src="https://github.com/phetsims/number-line-integers/assets/87318828/52564eb2-8851-44d7-91ca-24d571d48203">

Ex: Oromo
RC:
<img width="761" alt="Screenshot 2023-12-19 at 12 44 54 PM" src="https://github.com/phetsims/number-line-integers/assets/87318828/0bb1399d-f6bb-4a5c-854c-f85f1774f83a">

Published:

<img width="589" alt="Screenshot 2023-12-19 at 12 45 19 PM" src="https://github.com/phetsims/number-line-integers/assets/87318828/1a10c833-1aa9-415a-b2c2-6c82c979429a">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Sarara Lakkoofsaa: Lakkoofsota guutuu‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.2.0-rc.3/phet/number-line-integers_all_phet.html
Version: 1.2.0-rc.3 2023-12-13 17:13:14 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language: en-US
Window: 1429x728
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by marlitas** [comment]
Fixed above. Ready to cherry pick.

**Comment by Nancy-Salpepi** [comment]
looks good in rc.4. Closing.
