### ISSUE TITLE
Buttons in bank scene can allow two piggy banks to have the same balance

### ISSUE THREAD

**Issue by SaurabhTotey** [phetsims/number-line-integers#13]
In the bank scene, the two piggy banks cannot get the same balance if they are both dragged to the same value because one will bump off. However, when manipulated with the buttons, the two piggy banks can get to the same value. This is because the buttons directly set the values of the balance properties rather than going through the numberline to affect the balance properties. The number line is what enforces that each value only has a single point.

**Comment by SaurabhTotey** [comment]
Relatedly, this affects bank scene layering in that clicking the buttons doesn't update numberline points layering whereas dragging does.

**Comment by SaurabhTotey** [comment]
Also related is that when the scenes screen is reset, all association between the bank account balance and number line value is lost.

**Comment by jbphet** [comment]
I added a fix for this in https://github.com/phetsims/number-line-integers/commit/c86c2e8e2a57b0ecc33f5c2615ddc35d4240514f, but I'm going to review with @amanda-phet to make sure the behavior is what we're after.

**Comment by jbphet** [comment]
Should be fixed.  @amanda-phet - please test version https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-dev.7/phet/number-line-integers_en_phet.html and let me know if you're okay with the new behavior.

**Comment by amanda-phet** [comment]
I noticed that if I press and hold a button and one bank skips over the other, it still nudges the other one. However, if I'm dragging a pig past the other it doesn't happen. Ideally if we are quickly moving one pig past the other (either dragging the pig or using the buttons) it won't cause the other one to change value. Is it possible to make this happen when someone is pressing and holding a button to add/remove coins?

**Comment by jbphet** [comment]
I've modified the behavior so that the value swap only occurs if the user releases one of the buttons and causes the balances to be the same.  This seems more consistent with the dragging.  @amanda-phet - please test drive on master and see what you think.

**Comment by amanda-phet** [comment]
This is working well for me. Thanks for making that change!
