### ISSUE TITLE
Use equal sign when comparing two equal values

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-integers#130]
@Nancy-Salpepi was testing the sim and thought it was odd to see a statement like 0 ≤ 0. While it's not technically an incorrect statement, it makes you wonder why not just write 0 = 0. I am OK with this behavior when two objects/points temporarily occupy the same spot, until you drop the object and see something like 0 < 1, but not when there is no interaction happening. When you have only one point/object, I can't see a good reason for displaying 0 ≤ 0. 
![image](https://github.com/phetsims/number-line-integers/assets/7852916/8738e9ea-1d7c-4d95-8682-c46fdc71055e)

We need the original behavior when there are three points/objects (it would be really odd to see 0 = 0 < 1 in math and we don't want to encourage that). However, with only two, or one, an equal sign is perfect. 

I discussed this with @catherinecarter and @kathy-phet as well, and @marlitas found a non-intrusive way to make this change in the code.

**Comment by marlitas** [comment]
Committed above. Ready for cherry-pick

**Comment by Nancy-Salpepi** [comment]
This new change looks great!

When testing I noticed that in the Temperature scene, after the temperature of a thermometer changes so as not to be equal to another one, clicking on that thermometer, changes it back to the 'equal value'. This behavior is also seen in published, but doesn't occur in the other two scenes. Don't know if it's worth the time to fix this, but wanted to mention. 
Feel free to ignore and close! 

https://github.com/phetsims/number-line-integers/assets/87318828/34ddf71a-5eea-4e01-8073-b6906320120a

**Comment by marlitas** [comment]
Hmmm. It seems that clicking on the thermometer is causing enough movement to change the temperature a bit, which doesn't seem all that buggy to me. I think it's fine, especially since we see it in published. Thanks @Nancy-Salpepi! Closing.
