### ISSUE TITLE
New screenshots

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-integers#131]
New screenshots are needed since the bank change from a pig to a coin jar. I will do all screenshots for consistency (since the navbar is different, as well as the scene selection button on 3 of the screenshots).

**Comment by amanda-phet** [comment]
This is ready @marlitas . I accidentally had one file named incorrectly, so there are two commits.

**Comment by marlitas** [comment]
Marking for cherry pick

**Comment by marlitas** [comment]
This was cherry picked and the sim is now published. Thanks!
