### ISSUE TITLE
Design discussion 8/1/2019

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-integers#15]
I had a number of design questions for @amanda-phet, so we set up a discussion, here are some notes:

+ Should currency symbol translatable?
  + Yes.  @amanda-phet will modify the artwork for the deposit/withdraw icons to support this.  It will work best if the location of the coin is the same in both places.
+ The current artwork for deposit has two coins, but the value of the account only goes up by 1.  Should we modify?
  + Yes, @amanda-phet will modify.
+ The map in the design doc is more colorful than the one from Copernicus.  Are we okay with that?
  + Yep.
+ The temperature data that we got has values that go off the bottom of the number line.  Okay to just scale the number line so that all data fits?
  + Yep.
+ Okay to put the number line in the temperature scene in a panel?  The design doc shows it with a different background.
  + Yes, let's make the panel gray and with no stroke for now, and use the default corner rounding, and we can modify after review if needed
+ Per-scene reset?
  + Yes, @amanda-phet will work on this.
+ The artwork on the "Elevation" scene seems a little too detailed.
  + @amanda-phet will see if it can be simplified a bit.
+ The offsets for the images in the "Elevation" scene should be modified so that the absolute value indicators and point controller positions work better.
+ Should the dollar sign be shown for the number line labels on the "Bank" scene?
  + Yes, as is currently implemented looks good.
+ Note that on the number line in the "Temperature" scene, the labels need to move to the left side.
+ Do we need to inflate the movable point controllers in the "Elevation" scene.
  + No need.

**Comment by SaurabhTotey** [comment]
From the above issue, I believe all that's left is

> + Per-scene reset?
>   + Yes, @amanda-phet will work on this.
> + The artwork on the "Elevation" scene seems a little too detailed.
>   + @amanda-phet will see if it can be simplified a bit.

\
For
> + The offsets for the images in the "Elevation" scene should be modified so that the absolute value indicators and point controller positions work better.

there is code to easily tweak the center positions of the point controllers and the offsets of the absolute value texts relative to the image. I have already tweaked the centers and relative absolute value text positions to work/look slightly better.

**Comment by amanda-phet** [comment]
@jbphet and I discussed the reset today and he is going to add one to the temperature scene. 

The Elevation scene artwork has been simplified and committed.
