### ISSUE TITLE
Temperature scene absolute value text colors

### ISSUE THREAD

**Issue by SaurabhTotey** [phetsims/number-line-integers#18]
In the temperature scene, the colors of the absolute value texts can get really hard to read at low temperatures. The blue color is too similar to the black color and there is barely enough contrast to read it.

![BadColors](https://user-images.githubusercontent.com/22577113/62799100-22eb7980-ba9d-11e9-88da-956af0d11aa9.png)

**Comment by amanda-phet** [comment]
@arnabp came up with a dynamic solution that is working nicely. If the colors are light, they get a black background, and if the colors are dark, they get a white background.
