### ISSUE TITLE
update toggle artwork

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-integers#19]
I'd like to see if we can update the bank toggle artwork to match the new pigs. Can we do something like this?

![image](https://user-images.githubusercontent.com/7852916/62971501-3f562180-bdcf-11e9-8cf3-9e8473b45560.png)

I used the outlines from the pigs on the number line and gave the active side of the switch white backgrounds.

**Comment by SaurabhTotey** [comment]
I have implemented this change on master. The transparent piggy banks may be difficult to see. Assigning to @amanda-phet to review.

**Comment by amanda-phet** [comment]
I agree, the transparent pigs are too faint. Maybe we could do a white background when inactive, and green background when active?

**Comment by SaurabhTotey** [comment]
Here are what the toggles look like with different colors for backgrounds. For the different green color and the blue color, I just used the CSS default for 'green' and default for 'blue', but I can try more specific hex/rgba colors.

Piggy bank with same green as other piggy banks:
![WithSameGreen](https://user-images.githubusercontent.com/22577113/63046093-04b3be00-be8f-11e9-8819-3da914be54e1.png)

Piggy bank with CSS default for 'green':
![WithDifferentGreen](https://user-images.githubusercontent.com/22577113/63046095-067d8180-be8f-11e9-9aec-c9687bc16c19.png)

Piggy bank with CSS default for 'blue':
![WithBlue](https://user-images.githubusercontent.com/22577113/63046097-07aeae80-be8f-11e9-8cc0-60883e524134.png)

**Comment by amanda-phet** [comment]
I like the first option which uses the same green as the piggy banks.

**Comment by SaurabhTotey** [comment]
I have incorporated that green color into master. I'll close this issue now that everything has been addressed, but feel free to reopen if anything else needs to be done.
