### ISSUE TITLE
pixel polishes

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-integers#23]
General:
- [x] make the comparison statement wider
- [x] add space around expandCollapseButton
- [x] increase opacity of all transparent white backgrounds
- [x] increase font sizes of label all around (first: are they currently consistent in size?)

Elevation scene:
- [x] Change fish dot/line color to something brighter. Maybe #0092FF?

Bank scene:
- [x] Pigs should increase in opacity the farther they are from 0. Perhaps start with 20% opacity at 1 and go to 100% at 100. Might need a white background behind the green/red so the color doesn't blend with the background.
- [x] The $100 looks large. Reduce font size.
- [x] Pigs on toggle are hard to see. Perhaps add a black stroke around the pigs? gray fill instead of white? less opaque fill? 
- [x] Add a white background behind the "balance of..." text

Temperature scene:
- [x] Try another mercury color? Gray doesn't seem easy to see
- [x] The color of the numeral in the comparison statement doesn't update (bug)
- [x] Two thermometers can have the same value when switching months (bug)

Generic screen:
- [x] Make the orange color bolder (try #F7931E to start)

**Comment by amanda-phet** [comment]
>make the comparison statement wider

In addition to this change we made the < | > button a bit smaller 

> Change fish dot/line color to something brighter. Maybe #0092FF?

Instead of changing the color we reduced the opacity of the water and it seemed to brighten up nicely

**Comment by jbphet** [comment]
Over to @amanda-phet to review.  Everything in the list is checked off, so it would be good to take a look at the master version and see if the results look good.

One observation: I personally don't like the pig being white at zero.  To me, it creates a noticeable flash when sliding back and forth, and doesn't add much value.  I'd suggest just using an extension of the green color instead.

**Comment by jbphet** [comment]
@amanda-phet said that it's probably best to have there be no color for the piggy banks at the value of zero, since it makes it clearer that zero is neither positive nor negative, so the plan is to leave it the way it currently is.  @amanda-phet - anything else to do on this one?

**Comment by amanda-phet** [comment]
All looks good, thanks!
