### ISSUE TITLE
Currency units isn't fully translatable

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-integers#27]
The strings file has the following entry:
```json
  "currencyUnits": {
    "value": "$"
  },
```

...but also has:
```json
  "moneyAmount": {
    "value": "${{value}}"
  },
```

That's not going to work out well.  Strings that contain a dollar sign should be updated to allow the use of the translated currency unit.

**Comment by SaurabhTotey** [comment]
I changed moneyAmount to the below
```
"moneyAmount": {
  "value": "{{currencyUnit}}{{value}}"
},
```

Closing, but feel free to reopen if more changes need to be made.
