### ISSUE TITLE
change requests from interviews

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-integers#30]
I imagine the bugs should be individual issues, but before I go out of town and forget everything I am making a note in one place. All of these came out of interviews.

- [x] Should we rename the "scenes" screen to Explore? I never want to refer to it as the scenes screen. It's confusing internally, but is also a mess to say when referring to it as a screen. 
- [x] I notice the parachute is still layered over the numbers, but maybe that is fixed on master (I need to check) 
![image](https://user-images.githubusercontent.com/7852916/65534583-04123c80-debd-11e9-96fa-028cf3d8016d.png)
- [x] BUG: both pigs can be at the same value. I think this is easily reproduced when using the buttons.
![image](https://user-images.githubusercontent.com/7852916/65534557-f361c680-debc-11e9-82bf-633c743470d3.png)
- [x] It might be nice for the add/remove money buttons to match the bank account colors (blue and pink). A bright blue button is probably too much, so I might have to pick a tint of that blue, so I'll provide hex codes for that.
- [x] BUG: if you minimize the comparison statement then go to a different scene or screen where the accordion box is maximized, the text is overlapped
![image](https://user-images.githubusercontent.com/7852916/65534525-da591580-debc-11e9-8e31-ad0832a21cfc.png)
- [x] BUG: absolute value statement reads "-11 below 0" and should read "11 below 0"
![image](https://user-images.githubusercontent.com/7852916/65534657-25732880-debd-11e9-9840-7c5c29e23e93.png)
- [x] Generic screen: at 0, there should be an absolute value statement that reads |0| = 0
- [x] The absolute value label is the only one without the transparent white background, so I'd like one added to that

**Comment by jbphet** [comment]
@amanda-phet - I believe @SaurabhTotey and I have addressed the listed items, please verify on version https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-dev.7/phet/number-line-integers_en_phet.html.

**Comment by amanda-phet** [comment]
Verified all of those are looking good. 

One quick question- did the size of the font for the temperature here (-15º F) change intentionally or was that by accident?
![image](https://user-images.githubusercontent.com/7852916/66766896-76e35780-ee6c-11e9-97bf-0bd1bc434c26.png)

**Comment by jbphet** [comment]
> [D]id the size of the font for the temperature here (-15º F) change intentionally or was that by accident?

Oops - that was a bug that was introduced while added the ability to change the label font for the Generic screen.  Should be fixed.

**Comment by amanda-phet** [comment]
Looks good now :) Thank you!
