### ISSUE TITLE
Pixel polishes from 10/3/2019 review meeting

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-integers#33]
The sim was reviewed in design meeting today, here's what needs to be done as a result:
- [x] add a per-scene reset, use the small grayish undo button, but it above leftmost scene buttons
- [x] rename "Scenes" to "Explore"
- [x] make all the comparison statements the same size, make the "Elevation" scene image a little smaller so that this works
- [x] increase the label font size (the one with white background) to 18 on the generic number line
- [x] decrease amount of "leader" at ends of the number line to about half of what it currently is
- [x] enlarge the scene selection buttons such that the left side aligns with the checkboxes and the right side with the reset all button
- [x] made the size for the checkbox labels the same in the two screens, use size 16 font (which is smaller than what is currently used on the "Generic" screen
- [x] align the left side of the month selection combo box with the check boxes

**Comment by jbphet** [comment]
I believe all of the requested changes listed above have been addressed.  @amanda-phet - please take a look at https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-dev.7/phet/number-line-integers_en_phet.html and test whether the changes are what we're after.  If everything listed has been addressed, please close the issue.

**Comment by amanda-phet** [comment]
>add a per-scene reset, use the small grayish undo button, but it above leftmost scene buttons

Oops, I wanted this to be white! Just like in Unit Rates. 

>decrease amount of "leader" at ends of the number line to about half of what it currently is

I was hoping that by doing this, we could maximize the size of the number lines to fit the space. It seems like the bank, temperature, and generic number lines could all be larger now that the leader is smaller. Can we make that change? 

Everything else looks great!

**Comment by amanda-phet** [comment]
One more request about the per-scene reset: can you center it over the scene selection buttons too? Not sure I love the left placement.

**Comment by jbphet** [comment]
The three 2nd round revision requests have been made, details below.  Please check them on master and let me know what you think.

> Oops, I wanted this to be white! Just like in Unit Rates.

The reset button in Unit Rates is actually a light gray, so I matched the color used there.

> [C]an you center [the per-scene reset button] over the scene selection buttons too?

Done.

> I was hoping...we could maximize the size of the number lines to fit the space. 

I took a shot at this.  The bank scene is probably the trickiest because we need to make sure that the piggy banks never overlap with the buttons.  Please take a look at the revised sizes and, if you think we should make more adjustments, let me know and we should work on it together in real time.

**Comment by jbphet** [comment]
I moved the per-scene reset button to be centered above the selectors, and it gave me an idea: Since there is one per-scene reset button for each scene, what if we put the reset button for the scene above the selector for that scene?  It might make it more clear that it goes with the scene.

**Comment by amanda-phet** [comment]
The larger number lines are great! Thanks! 

The other changes look good. Happy to discuss moving the reset button above each scene selection if that's an easy change to try out.

**Comment by jbphet** [comment]
@amanda-phet - we were going to potentially discuss the moving scene reset buttons at design meeting this week, but we didn't get a time slot.  I think you and I should make a call as to whether to leave it as is or add the feature and see what we think.  I'd estimate about an hour to add it and publish a dev version for evaluation.  What's your opinion - worth it or not (I'm not attached to the idea)?

**Comment by amanda-phet** [comment]
@jbphet and I discussed this in-person last week and we decided to just leave the scene reset button as it is. If @ariel-phet or @kathy-phet  would like to tweak it, let's re-open the issue.
