### ISSUE TITLE
Adjust the pointer areas for better usability on touch devices

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-integers#34]
In the 10/3/2019 review meeting for this sim, @kathy-phet suggested that we go through and adjust the pointer areas, since she found it tricky to use on her phone.  Since the sim is pretty much functionally complete, it would be a good time to that now.

**Comment by jbphet** [comment]
At a review of this sim today, @kathy-phet had two suggestions:

+ increase the pointer area for the combo boxes
+ increase the size of the pointer areas for the point controllers such that they are easier to grab from further away from the number line.  See the screenshots below - the yellow portion indicates the extension (roughly)

![image](https://user-images.githubusercontent.com/3082831/67599243-e0951880-f72c-11e9-85b4-21dbcec10ffe.png)

![image](https://user-images.githubusercontent.com/3082831/67599415-3cf83800-f72d-11e9-81fc-58544805dbf9.png)

**Comment by jbphet** [comment]
@SaurabhTotey and I have implemented larger and asymmetric touch areas.  I've tested them on my Win 10 computer with touch screen, and they seem to work pretty well.  @kathy-phet - can you test on your phone and give us feedback?

![image](https://user-images.githubusercontent.com/3082831/68061542-01c8ac80-fccb-11e9-9b14-efbbc58c5bec.png)

![image](https://user-images.githubusercontent.com/3082831/68061549-0db46e80-fccb-11e9-90c0-74ad1de31200.png)

**Comment by KatieWoe** [comment]
For https://github.com/phetsims/QA/issues/457.  They seem a bit large to me, especially since they go out of the toolbox.  Haven't used on a small screen yet, so reserving judgement in that area.

**Comment by amanda-phet** [comment]
@KatieWoe said
>They seem a bit large to me, especially since they go out of the toolbox.

Can you clarify what you mean by "they go out of the toolbox"? Do you mean the points when they are still in the panel and not on the number line?

**Comment by kathy-phet** [comment]
@KatieWoe - They are the way they are so that you can pick them up but have your finger out of the way on a small touch device. Previously, it was not possible to control it without also obscuring the point on the numberline - on a small device. Just FYI - so when you evaluate it you know what the goal was.

**Comment by KatieWoe** [comment]
@amanda-phet yes that is what I mean

**Comment by jbphet** [comment]
@KatieWoe and @kathy-phet - we're getting close to an RC on this one, so I need your input on what, if anything, you feel needs to change from the current implementation.  The current dev version has the latest in terms of these pointer areas, see https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-dev.10/phet/number-line-integers_en_phet.html?showPointerAreas.

**Comment by KatieWoe** [comment]
If what was described in https://github.com/phetsims/number-line-integers/issues/34#issuecomment-554046452 is deemed fine then I don't think I have anything to add.

**Comment by kathy-phet** [comment]
This is working well for me. I can adjust the points and still see all the values at the same time. Closing.
