### ISSUE TITLE
Changes to "zero"

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-integers#35]
Since zero is neither positive nor negative, we need a few special behaviors at 0. 

**Elevation scene**
- [x] When an item is at 0m, the absolute value text should say "sea level" instead of "0m above sea level." 
- [x] If possible, the items at 0m should maintain the state they were in as they approach 0. So, if dragging up, a bird might be diving at -1m and at 0m, is still diving. If dragging downward, the bird might be flying at 1m and at 0m, is still flying. Can we do this? 

**Bank scene**
- [x] When a bank is at $0, the absolute value text should continue to say "balance of $0" but the text should be black, not green.

**Temperature scene** 
(This is very difficult to produce, but we need a way to handle it should it occur.)
![image](https://user-images.githubusercontent.com/7852916/66768210-49e47400-ee6f-11e9-84fe-1a19efb936de.png)

- [x] When a thermometer is at 0º, the absolute value text should say "0º" and should *not* indicate above or below 0.

**Comment by jbphet** [comment]
@amanda-phet - I've implemented these changes on master, please check them out and let me if they look okay.

**Comment by amanda-phet** [comment]
All look great to me. Thanks so much.
