### ISSUE TITLE
static getters in es6 classes is bad-sim-text

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-line-integers#37]
Since some work was done on https://github.com/phetsims/chipper/issues/791 a few weeks ago, the `bad-sim-text` lint rule has not been working right. As a result, it didn't error on static getters added in `BankSceneModel.js`. I added `// eslint-disable-line bad-sim-text`, but this isn't good enough. We don't support them because Babel doesn't transpile them appropriately. see https://github.com/phetsims/tasks/issues/983.

**Comment by jbphet** [comment]
Thanks @zepumph - good to know.  I've modified these static properties to use the approach elucidated in https://github.com/phetsims/wave-interference/issues/281#issue-392730446.  Closing.
