### ISSUE TITLE
Update font sizes

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-integers#38]
@kathy-phet, @amanda-phet, and I met today to do more "pixel polishing" on this sim.  Font sizes were one of the big discussion items, here is what I took from the meeting:

+ Most if not all of the fonts associated with readouts of variable number information should have a point size of 18.  This will make them easier to read on phones and also in the back of the room if used on projectors.  This includes all absolute value indicators
+ Tickmarks for the number lines should have a point size of 16 (which is what they currently have)

**Comment by jbphet** [comment]
These adjustments should be made.  @kathy-phet and/or @amanda-phet - please look them over on master and let me know if further changes are needed.

**Comment by amanda-phet** [comment]
All of the fonts look correct to me. 

@kathy-phet please close if it looks good to you.

**Comment by jbphet** [comment]
@kathy-phet - I'm about to do an RC, last chance for input on this one.

**Comment by kathy-phet** [comment]
All the font sizes look good to me.
