### ISSUE TITLE
Make the checkboxes match the text height

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-integers#40]
The checkboxes are currently significantly bigger than the text labels, and should be reduced to match.  This was recently done for Gas Properties as part of the pixel polishing, so that can be used as an example.

**Comment by jbphet** [comment]
I attempted to stylistically match what is currently live in Gas Properties, where it looks like the upper and lower edges of the checkboxes go just above and just below the largest letter.  Below is what it looks like.  Does this fit the bill?

**Comment by jbphet** [comment]
It looks like this:

![image](https://user-images.githubusercontent.com/3082831/67610105-d6cfdd00-f74d-11e9-9807-f1120974dd07.png)

**Comment by amanda-phet** [comment]
These look too small to me. Here are some recently published sims that I would prefer to match:

![image](https://user-images.githubusercontent.com/7852916/67710169-13d1e480-f985-11e9-9417-827180724d4f.png)

![image](https://user-images.githubusercontent.com/7852916/67710112-f13fcb80-f984-11e9-8425-d18c118007f2.png)

**Comment by kathy-phet** [comment]
@ariel-phet - Tagging Ariel here, since it was brought up by him at a recent design meeting. Perhaps the designers should set a standard together here - since its a bit all over the map.

**Comment by ariel-phet** [comment]
To me, it is the check boxes should be "approximately" the same vertical size as the first uppercase label letter. A bit bigger is fine with me, but in some cases we will need things to be more compact. It is more in very early sims the check boxes were kind of over-the-top huge.

I am fine with sizes that are about the size of the first uppercase letter or a bit larger.

**Comment by amanda-phet** [comment]
@jbphet can we move forward with a slightly larger checkbox that matches what is done in EFAC?

**Comment by jbphet** [comment]
This is with a checkbox `boxWidth` of 17, which is about 13% bigger than the previous version and 20% smaller than it was originally, when it was using the default value of 21.  @amanda-phet - please have a look.  If further tweaking is necessary, let's do it together in person or over Zoom.

![image](https://user-images.githubusercontent.com/3082831/68343991-4aa5aa00-00ab-11ea-986d-dabbe1c3b495.png)

**Comment by jbphet** [comment]
I talked with @amanda-phet, and she said the new size looks good.  Closing.
