### ISSUE TITLE
Find a better color for the orange point controller on the "Generic" screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-integers#41]
@kathy-phet has suggested that we try to find a color with more contrast for the orange point controller on the Generic (2nd) screen.

![image](https://user-images.githubusercontent.com/3082831/67598494-e427a000-f72a-11e9-8af6-47668232d0f2.png)

**Comment by amanda-phet** [comment]
This orange is nearly identical to the orange used in Vector Addition. It is likely the background color that makes it seem different here (since it's not white). 

I updated the color to #ff8a15 on master. @kathy-phet see if that works for you. If not, I will look for an entirely new color, or perhaps 3 new colors.

**Comment by kathy-phet** [comment]
Thanks, Amanda. This does make a difference. I think it works enough better to go with it. 

Can we change the default starting point too? So that we start with the very high contrast blue point out, and the pink and orange in the bin?

**Comment by amanda-phet** [comment]
>Can we change the default starting point too? So that we start with the very high contrast blue point out, and the pink and orange in the bin?

I love that idea! The blue is my favorite, so I say we start with that as the default color. The other points can stay in their current location in the panel, we just need to put the blue point at 1 on the number line and keep the orange one in the panel. @jbphet off to you.

**Comment by jbphet** [comment]
> The other points can stay in their current location in the panel, we just need to put the blue point at 1 on the number line

@amanda-phet - The way the panel is implemented it fills from left to right, and I didn't want to change this unless I really needed to, so the initial arrangement has changed a bit.  I like it, since the initial position of blue point on the number line is close to where it goes in the panel.  Please have a look, and close this if you're okay with it.

**Comment by amanda-phet** [comment]
I just meant you can do whatever is simplest, so if having the blue point be the rightmost point is the simplest then that is fine!
