### ISSUE TITLE
Consider moving things down a bit on bank and temperature scenes

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-integers#42]
@kathy-phet was just looking over the sim and felt that there was a fair amount of white space below the interactive area in the "Bank" and "Temperature" scenes.  Should these be moved down a bit?  We may want to reposition the scene selector buttons too if so.

**Comment by kathy-phet** [comment]
Another reason to move the scene down is that there is an overlap issue in this case: 
![image](https://user-images.githubusercontent.com/5096804/67603642-b9dbdf80-f736-11e9-8eed-e6b5df8b88f2.png)

**Comment by kathy-phet** [comment]
On Temperature screen, moving it down will help with this overlap. 
![image](https://user-images.githubusercontent.com/5096804/67604322-8437f600-f738-11e9-82b1-01069f60eb78.png)

**Comment by amanda-phet** [comment]
I agree that everything could be moved down a little (perhaps less on the bank scene though). 

I'm not sure how to reproduce that overlap on the bank scene-- how did you do that? Here is what I see:
![image](https://user-images.githubusercontent.com/7852916/67709703-197afa80-f984-11e9-98cf-13128d005184.png)

**Comment by jbphet** [comment]
> I'm not sure how to reproduce that overlap on the bank scene-- how did you do that? Here is what I see:

This was due to some undesirable interactions between the coin animations and the label positions, and was fixed a while ago, see https://github.com/phetsims/number-line-integers/issues/46.

**Comment by jbphet** [comment]
I've moved the temperature map down as much as I think I can without there starting to be too much space above it.  I didn't move the bank scene contents down because it doesn't seem to me to need it visually, and the issue with the overlap between the label and the comparison statement is now resolved.  @amanda-phet - please review and let me know if you think for changes are needed.

**Comment by amanda-phet** [comment]
The map and banks look fine to me, but now I'm noticing that the thermometer panel is in a funny location. Seems like it should be bottom-aligned with the temperature panel, and hopefully also bottom-aligned with the panel in the Elevation scene. If it's possible to tweak those a bit so there is some consistent alignment that would be great. Sorry I didn't get this request in before rc.1!

**Comment by kathy-phet** [comment]
@amanda-phet - If we do this, then maybe recenter the globe image between the comparison statement and the thermometer panel - shifting it down a bit?

**Comment by amanda-phet** [comment]
Sure, that sounds fine to me. Maybe the 3 of us can pixel-polish together in-person?

**Comment by jbphet** [comment]
@amanda-phet and @kathy-phet - the changes that we discussed in the pixel-polish meeting are on master, please take a look and let me know whether you think further work is necessary.  Please make sure you assign this back to me when you're done so that I can make sure all changes get propagated to the release branch.

**Comment by kathy-phet** [comment]
Looks good to me.

**Comment by amanda-phet** [comment]
It all looks good to me.

**Comment by jbphet** [comment]
I've committed the approved layout adjustments to the release branch and will have them verified as part of the next RC test.

**Comment by KatieWoe** [comment]
Things are looking ok. I really only notice the change on the thermometer scene though.
