### ISSUE TITLE
Increase the "disconnect" distance

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-integers#43]
@kathy-phet was testing this sim on a phone and found that it was a little too easy to remove points from the number line when just trying to get one's finger out of the way in order to see the number line better.  We should increase the tolerance for this, which essentially means to increase the "point removal" distances for both the horizontal and vertical number line orientations.

**Comment by jbphet** [comment]
I've increased the point removal distance by roughly 50%.  In the horizontal number line orientation, this means that the user needs to drag a bit over half way back to the storage box before the points release, so I don't want to go too much beyond this amount.  @kathy-phet and @amanda-phet - please give this a try and give me your feedback.

**Comment by amanda-phet** [comment]
I think this is too far. Can we scale back a bit? Maybe what would have been 35%?

**Comment by kathy-phet** [comment]
I agree it seems too much now. Maybe split the difference. On the phone it seems like it could be less than it is now and still work.

**Comment by jbphet** [comment]
I've adjusted it down a bit, basically splitting the difference as suggested.  @kathy-phet and @amanda-phet - please try it now (on master) and see what you think.

**Comment by amanda-phet** [comment]
This works for me. @kathy-phet if you like it then I'm fine if you close this issue!

**Comment by jbphet** [comment]
Since @amanda-phet approves and @kathy-phet hasn't responded, I'm going to go ahead and close this one.
