### ISSUE TITLE
Suggestion: Add a "Label" check box to the "Explore" screen

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/number-line-integers#45]
It occurred to me while I was playing with this screen, that it would be useful to be able to hide the labels - just like we do on the second screen. I think @amanda-phet and I may have discussed this previously as it feels familiar? On each scene this would hide the label on the numberline, and additionally in the bank scene it would hide the value on the piggy bank. 

This would add uniformity across the screens, and functionality - allowing students to do some estimating, or to reason without numbers about which was bigger.

I'm not sure what the default would be. Note on the Generic Screen, the default is currently off.

**Comment by jbphet** [comment]
This seems like a reasonable suggestion to me, and I particularly like the idea that it could be turned off and students would need to estimate values, which could help to develop more intuition about scale and about how the numbers are there whether or not they see them.  

In my opinion, the default should be on.

@amanda-phet - since you're the head designer, I'm assigning to you for a 'yay' or 'nay' before I move forward with implementation.

**Comment by amanda-phet** [comment]
Sure, let's add labels. I agree they should be on by default on the Explore screen.

**Comment by kathy-phet** [comment]
@amanda-phet - If default is "labels" on on the Explore. It seems like we should match that default and make it "on" on the Generic too, since that is probably how most people will want to use it? What do you think?

**Comment by amanda-phet** [comment]
That's fine with me. I usually want it on every time I go to the Generic screen :)

**Comment by jbphet** [comment]
I've implemented a version of this and have two questions:

+ Is the checkbox order okay?
+ Shall we also hide the thermometer letter labels?  I have opted **not** to do so in what I've done so far, since I don't see any value in hiding these, and it would make it harder to match the thermometer values to the positions on the number line.

**Comment by amanda-phet** [comment]
>Is the checkbox order okay?

Let's put Labels first, to match the Generic screen.

>Shall we also hide the thermometer letter labels? I have opted not to do so in what I've done so far, since I don't see any value in hiding these, and it would make it harder to match the thermometer values to the positions on the number line.

My understanding of this checkbox is it shows/hides the labeled value on the number line. So, it would not be consistent for it to hide anything else, such as the letter labels.

**Comment by kathy-phet** [comment]
Amanda- to share the reason I recommended labels second is because you cannot actually hide the numberline at all on the generic screens and I didn’t think it was something you would want to do much of, so I thought put it at the top with default on since that would keep the order of the other boxes consistent with the generic screen?

Sent from my iPhone

On Nov 4, 2019, at 2:51 PM, Amanda McGarry <notifications@github.com<mailto:notifications@github.com>> wrote:


Is the checkbox order okay?

Let's put Labels first, to match the Generic screen.

Shall we also hide the thermometer letter labels? I have opted not to do so in what I've done so far, since I don't see any value in hiding these, and it would make it harder to match the thermometer values to the positions on the number line.

My understanding of this checkbox is it shows/hides the labeled value on the number line. So, it would not be consistent for it to hide anything else, such as the letter labels.

**Comment by amanda-phet** [comment]
>the reason I recommended labels second is because you cannot actually hide the numberline at all on the generic screens and I didn’t think it was something you would want to do much of, so I thought put it at the top with default on since that would keep the order of the other boxes consistent with the generic screen?

I didn't know it was intentional. That is fine with me.

**Comment by jbphet** [comment]
Issue #51 is another good reason why the "Labels" checkbox should be below the "Number Line" checkbox - it should be disabled when the number line is not visible.

I think we're basically done with the process of adding this control, so I'm going to close the issue.
