### ISSUE TITLE
Absolute Value Label needs to pop back into position if coins stop dumping in

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/number-line-integers#46]
Add coins. When they stop, absolute label value isn't "listening" and repositioning. 
![image](https://user-images.githubusercontent.com/5096804/67603718-e132ac80-f736-11e9-8739-a528794e94b4.png)

**Comment by jbphet** [comment]
I tried a number of different approaches for this, and most ended up with some odd and/or distracting animation of the label position.  I ended up going for something simple - the labels just maintain a constant relationship to the edge of the piggy banks.  This will overlap with the coin animations in some cases, but I found this to be less objectionable than having them jump around.  @kathy-phet - please try this out on master and see if it seems reasonable.

**Comment by kathy-phet** [comment]
This looks good to me. Thanks!

**Comment by amanda-phet** [comment]
Ah, I see what was happening in that other issue now! I like the behavior I'm seeing on master right now where the coins animate behind the label.

**Comment by jbphet** [comment]
Sounds like the updated behavior is approved.  Closing.
