### ISSUE TITLE
Overlap issues on absolute value of vertical "generic" screen

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/number-line-integers#48]
I was just playing an noticed some overlap issues with the absolute value reading in the vertical generic screen. @amanda-phet - did you consider possible rotating the absolute value readouts so they are more like in the horizontal screen? 
![image](https://user-images.githubusercontent.com/5096804/67815017-57068300-fa6b-11e9-8b91-4cd350c78f40.png)

**Comment by amanda-phet** [comment]
I think that this is because we increased the font sizes, so @jbphet can probably tweak the spacing.

At one point I think we considered rotating the text, but I don't think that's very user-friendly, especially for younger audiences. I think it might be best to tweak the spacing.

**Comment by amanda-phet** [comment]
@jbphet can you adjust the spacing for these labels?

**Comment by jbphet** [comment]
@amanda-phet - you're correct, this is a result of the recent font size changes.  I adjusted the distance for the absolute value span that is closest to the number line based on what I believe is the worst case alignment (see below).  Please check this and close if it looks good.

![image](https://user-images.githubusercontent.com/3082831/68055385-25cdc300-fcb6-11e9-9d05-01a405abbdc4.png)

**Comment by amanda-phet** [comment]
Those look good to me. Thanks for making those adjustments. I couldn't find any other opportunities for the text to overlap.
