### ISSUE TITLE
Pixel polish: Consider making tick marks less prominent? 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/number-line-integers#49]
In a scene like this one, I find the tick marks and number labels on the numberline to be pretty prominent and competing with the points themselves. I thought maybe if the ticks in the middle (not the ends) of the number line were narrower or a dark grey or both that might help with the feeling of competition for attention? Thoughts?
![image](https://user-images.githubusercontent.com/5096804/67815252-0a6f7780-fa6c-11e9-96ce-a3542665b866.png)

**Comment by amanda-phet** [comment]
My preference would be to keep it the way it is. It only seems to be an issue when the NL in this exact configuration (I don't find it to be an issue when the NL is horizontal, or when the range is one of the other selections). 

The tick marks give a sense of scale, and while I wouldn't mind making some tick marks smaller, it wouldn't make much sense at the other ranges.

**Comment by jbphet** [comment]
I'm going to do an RC quite soon, so @kathy-phet - now is your chance if you'd like this to change.

**Comment by kathy-phet** [comment]
OK - we are leaving these as is. Closing.
