### ISSUE TITLE
Checkbox for number line and labels

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#51]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
Testing master per @jbphet request.
On the explore screen, you can turn on/off both the number line and the labels. However, the labels will only appear if the number line is there. Because of this, it makes more sense to have the labels checkbox be a subset of the number line checkbox, as seen in the WI example below.

**Visuals**
![nlcheck](https://user-images.githubusercontent.com/41024075/68330332-4ddf6c80-0090-11ea-914e-0522c833aa77.png)
![nlnotcheck](https://user-images.githubusercontent.com/41024075/68330333-4e780300-0090-11ea-8ae0-b26a9f483dcc.png)
Example:
![likethis](https://user-images.githubusercontent.com/41024075/68330342-53d54d80-0090-11ea-9763-abfdf1e4e02d.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: http://phettest.colorado.edu/number-line-integers/number-line-integers_en.html?ea&brand=phet
Version: 1.0.0-dev.7 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
I can see this being a good idea. If number line is off, then the labels checkbox doesn't do anything.

**Comment by jbphet** [comment]
@amanda-phet and I discuss this and decided to make the "Labels" checkbox go disabled when the number line is not visible, but we decided **not** to indent it, at least for now.  This is because the alignment just looks better this way, and we don't expect that people will disable the number line very much anyway, so we might as go with the alignment with the best aesthetics.  

@amanda-phet - over to you for review and to decide if you want anyone else's input on this.

**Comment by amanda-phet** [comment]
I this this looks good and functions well. Thanks all!
