### ISSUE TITLE
No indication of opposites if another point is in that spot

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#52]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
Testing on master for @jbphet.
I noticed that, if you put a second point over an "opposite" point, there is no indication of information under that second point. I wonder if it would be worth finding some way to indicate there is an opposite point there.

**Visuals**
![someindicate](https://user-images.githubusercontent.com/41024075/68332682-75d0cf00-0094-11ea-9f4d-2ecbce9a63ca.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: http://phettest.colorado.edu/number-line-integers/number-line-integers_en.html?ea&brand=phet
Version: 1.0.0-dev.7 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by amanda-phet** [comment]
This is not a bug. 

I don't have an issue with this overlap, because the points are each others' opposites! I also didn't notice any issues with this in particular in interviews, so I'm fine not addressing this.
