### ISSUE TITLE
Use PHET_CORE/Orientation instead of NumberLineOrientation

### ISSUE THREAD

**Issue by samreid** [phetsims/number-line-integers#53]
In https://github.com/phetsims/phet-core/issues/76 we generalized an `Orientation` enumeration in PHET_CORE.  It seems like this sim could used it, and delete `NumberLineOrientation`.  Assigning to responsible dev.

**Comment by jbphet** [comment]
Thanks for creating this enum @samreid.  It's been integrated into NLI.  Closing.
