### ISSUE TITLE
Dot leaves behind the piggy bank

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#56]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome/Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/457.  After a reset of the Explore page, the bottom piggy bank stops moving with the dot on the number line when changing the values with the add/subtract money buttons.  The piggy bank also does not move if you use the grey reset scene button.
**Steps to reproduce**
1. Refresh the sim
2. Go to the Explore screen
3. Hit the orange reset button
4. Go to the piggy bank scene
5. Use the buttons to add/subtract money
6. Drag the bank around
7. Hit the scene reset button

**Visuals**
![banksareodd](https://user-images.githubusercontent.com/41024075/68877460-5bfe4000-06c3-11ea-9f3c-ea8c290fb78b.gif)
![howdid](https://user-images.githubusercontent.com/41024075/68877494-67516b80-06c3-11ea-9e9d-e6550fc4e1e4.png)
![howdidtwo](https://user-images.githubusercontent.com/41024075/68877495-67516b80-06c3-11ea-82bb-5127e3c06c03.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-dev.9/phet/number-line-integers_en_phet.html
Version: 1.0.0-dev.9 2019-11-13 22:18:32 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment]
This was because I'd recently added a reset of the individual number lines to the "Explore" screen reset function in order to be thorough.  It turns out that this removes and re-adds the point that was associated with the primary account control, so the association between the two goes away.  I've removed that portion of the reset function.

@KatieWoe - can you please test this on master and verify that it's fixed?

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by jbphet** [comment]
Cool, thanks, closing.
