### ISSUE TITLE
Multitouch adding and removing coins at the same time

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#59]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/457. Fairly minor.
When you press both the add and subtract coins buttons for a bank at the same time two different behaviors can occur. The first is that the bank does not change at all. This occurs if you start both buttons at the same time. The second behavior is that the bank quickly oscillates between two numbers.  This happens if you start with one button, and then add the second while the bank is moving.

**Visuals**
![smoothortwitchy](https://user-images.githubusercontent.com/41024075/68887856-fb78fe00-06d6-11ea-9df6-161e9f355797.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-dev.9/phet/number-line-integers_en_phet.html
Version: 1.0.0-dev.9 2019-11-13 22:18:32 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment]
@KatieWoe - I added a "lockout" sort of thing to prevent one button from being used when the other is pressed.  Please check this out on master to see if it solves the problem and doesn't seem to introduce anything undesirable.

**Comment by KatieWoe** [comment]
Looks ok for the most part.  On win 10, letting go after attempting to press the second opens the left click menu and interrupts the first button.
![oddattempt](https://user-images.githubusercontent.com/41024075/68976832-fb026500-07b3-11ea-832d-30c79f0cad40.gif)

**Comment by jbphet** [comment]
I'm able to duplicate the behavior, but I looked it up and it is intentional for Windows 10, so it's not a problem with this sim.  Seems like the basic issue has been addressed, closing.
