### ISSUE TITLE
Diver can be placed underneath the play area

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/number-line-integers#60]
**Test device**
Windows 10 laptop
**Operating System**
Windows 10 
**Browser**
Chrome 78.0.3904.97
**Problem description**
From https://github.com/phetsims/QA/issues/457

The diver can be placed just underneath the play area. Will not return to original position, but also does not display a greater than or less than value since it is technically below -80m.
**Steps to reproduce**
1. Place diver just below play area such that it is barely on it.
**Visuals**

![Screen Shot 2019-11-14 at 3 29 38 PM](https://user-images.githubusercontent.com/54685448/68902293-24a88700-06f5-11ea-8637-9a3d2bef1e99.png)

![Screen Shot 2019-11-14 at 3 53 46 PM](https://user-images.githubusercontent.com/54685448/68903349-1ad45300-06f8-11ea-89b1-a8a5b876aba7.png)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-dev.9/phet/number-line-integers_en_phet.html
Version: 1.0.0-dev.9 2019-11-13 22:18:32 UTC
Features missing: generatedcontent, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Language: en-US
Window: 1536x754
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by KatieWoe** [comment]
This can be very tricky to reproduce.  Trying to see if it can occur on temp screen.  Don't see how it would on bank screen.

**Comment by KatieWoe** [comment]
Can also be above:
![bugpic](https://user-images.githubusercontent.com/41024075/68969401-1bc1bf00-07a2-11ea-99e0-e77bf3b3a4b3.png)

**Comment by jbphet** [comment]
This should be fixed in master now.  @KatieWoe or @loganbraywork - please verify.

**Comment by KatieWoe** [comment]
Seems fixed in rc.1. Closing, but will reopen if we find it again. It can be hard to reproduce.
