### ISSUE TITLE
Thermometer label string keys

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-line-integers#64]
For #62.

All the string keys look good. One nitpick I have is for these three - I don't see a reason for their keys to not just be "a", "b", and "c", as I thought we used suffixes like "Label" in keys for strings that were very long or not possible to match with the key.

```
"thermometerALabel": {
  "value": "A"
},
"thermometerBLabel": {
  "value": "B"
},
"thermometerCLabel": {
  "value": "C"
},
```

**Comment by jbphet** [comment]
@chrisklus - I see your point here, and I think in most situations I'd agree, but in this particular case I think having "thermometer" in the name is important.  My reasoning is that these labels appear in a scene that is not initially visible on any screen, so translators may have a tough time figuring out what they correspond to unless the key name carries a bit more of a hint.  So, unless you feel strongly on this, I'd prefer to leave them as they are.

**Comment by chrisklus** [comment]
Ah, that makes sense - thanks for the explanation. Sounds good to me, closing.
