### ISSUE TITLE
Write model.md description

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-line-integers#65]
For #62.

`model.md` is missing its description.

**Comment by jbphet** [comment]
@chrisklus - I've filled out model.md with a description of the underlying model and how it works.  Please have a look and let me know if you think it fits the bill and, if so, close.  If you have suggestions on how to improve it, assign back to me and I'll incorporate them.

**Comment by chrisklus** [comment]
Looks great @jbphet! Closing.
