### ISSUE TITLE
Factor out comparison signs in ComparisonStatementNode

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-line-integers#67]
For #62.

I see 8 usages of '<' or '>' in ComparisonStatementNode, so those should be factored out as file strings.

It would also be beneficial to add more validation to `this.selectedOperatorProperty`, perhaps with an option like `validValues: [ lessThanString, greaterThanString ]`

**Comment by jbphet** [comment]
Good suggestion, I've implemented both suggestions. @chrisklus - I'm just going to close this, since the change was pretty straightforward, but feel free to inspect my changes if you see it go by and are so inclined.
