### ISSUE TITLE
Evaluate absVal naming

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-line-integers#68]
For #62.

In primarily AbsoluteValueSpanNode.js and SpatializedNumberLineNode.js, the abbreviations absVal or ABS_VAL is used all over in variables, constants, and local types. 

In AbsoluteValueSpanNode.js, I saw no reason to just use the full words in all cases, and added a couple review comments that indicated as such. Then I came to SpatializedNumberLineNode.js, and saw that some longer variable names were being used, and a couple lines where expanding the abbreviations would extend the line beyond the max character length. So I realize the naming in AbsoluteValueSpanNode.js may have just been for consistency. I'll leave this to @jbphet to decide if any renaming is desirable.

In my opinion, 'abs' might be a standard enough abbreviation to be acceptable (`Math.abs()`), but 'value' seems preferable to 'val'.

**Comment by jbphet** [comment]
Good suggestion, guess I was just having lazy fingers.  All usages of ABS_VAL and absVal have been expanded.  Closing.
