### ISSUE TITLE
finalize the credits

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-integers#7]
Before initial publication, the credits in `number-line-integers-main.js` need to be correct.

**Comment by jbphet** [comment]
@KatieWoe - please let me know who to put in the final list of QA credits.

**Comment by KatieWoe** [comment]
At the moment: Logan Bray, Liam Mulhall, Jacob Romero, Kathryn Woessner
I'll slack you with any additions made in the next rc.

**Comment by jbphet** [comment]
I've made the updates described and put them on both the master and 1.0 branches.  Unassigning for now, please assign back to me if additional changes are needed.

**Comment by chrisklus** [comment]
Before I publish - is this issue all set @KatieWoe?

**Comment by KatieWoe** [comment]
Yes

**Comment by chrisklus** [comment]
Great, thanks. Closing.
