### ISSUE TITLE
Suggestion for the temperature scene

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/number-line-integers#72]
I was reviewing RC.1, and had this one thought. Should the value readings and "A", "B", "C" labels in the temperature number line have the same color treatment as the "absolute value" labels get - so there is a constant color match, like in the other scenes? (sorry its post RC.1, just came to me now).

**Comment by amanda-phet** [comment]
I'm not sure I understand. Do you mean you would like the text to be color-coded? You can see in dev.7 that it used to be, but some colors require a light background and others require a dark background, and the flickering background didn't look good. 

Please correct me if you're thinking of something else!

**Comment by kathy-phet** [comment]
I'm thinking color coded like this -- using the same solution as now is used for absolute value.
![image](https://user-images.githubusercontent.com/5096804/71854754-640fa600-309c-11ea-9bfd-d90a32e49901.png)

**Comment by amanda-phet** [comment]
I see what you mean now. 

@jbphet can we add the same color-coded background to the labels right next to the number line?

**Comment by kathy-phet** [comment]
I like the new style - it seems to really bring some nice pop/warmth to the numberline view. @amanda-phet what do you think?

**Comment by amanda-phet** [comment]
I like it. Thanks for making this change @jbphet !

**Comment by jbphet** [comment]
I've propagated the approved changes to the 1.0 release branch and will have this tested in the next RC.

**Comment by KatieWoe** [comment]
Looks good in rc.2
