### ISSUE TITLE
Numbers on Generic Screen shift off-center permanently after using 3 dots

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#73]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/465. 
When on the generic screen, the numbers displayed in the box near the top of the screen are centered. When you add a third point, and then take it away, the two remaining numbers are off center to the left and stay that way. This is still the case even if you reset the sim.
**Steps to reproduce**
1. Refresh the page
2. Go to the second page
3. Note the positions of the numbers in the box at the top of the screen
4. Add all the points to the line
5. Take away one or two of those points
6. Note the positions of the numbers in the box again

**Visuals**
![movingthreealigatorsfinal](https://user-images.githubusercontent.com/41024075/72019406-dd3b0480-3226-11ea-88b9-3ad7099b5c43.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-rc.1/phet/number-line-integers_en_phet.html
Version: 1.0.0-rc.1 2020-01-06 19:43:39 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Also occurs on the two Explore screen scenes with three points.

**Comment by jbphet** [comment]
Nice catch @KatieWoe.  This was a result of the optimization work that was done for #71.  

The change in alignment that is reported above was caused by an invisible comparison operator that was being left in place.  I have addressed this by moving unused comparison operator nodes to a position where they should have no impact.  This has been done on both master and the 1.0 branch.

**Comment by KatieWoe** [comment]
This looks fixed in rc.2
