### ISSUE TITLE
Layering of absolute value labels

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#74]
For https://github.com/phetsims/QA/issues/465.
I noticed that, on the first screen, the absolute value labels are on the same layer as their point. On the scene with the person, fish, and bird, this can lead to obscuring effects. I wonder if a different layering order may be better. (This does occur on the climate scene, but since the thermometers are larger it less of an issue.)
![possiblelayeringthought](https://user-images.githubusercontent.com/41024075/72020768-bdf1a680-3229-11ea-8bfe-f76964aa8246.png)

**Comment by ghost** [comment]
Here's a related nitpick:

![Screen Shot 2020-01-08 at 3 26 39 PM](https://user-images.githubusercontent.com/31285590/72021496-5f2d2c80-322b-11ea-9349-e24b29e4417f.png)

For example, the values for the piggy banks overlap. The label is slightly transparent. On the one hand, this lets a user know that there is something behind the label. On the other hand, it looks bad. (There are other instances of this in the sim.)

I can't imagine that we'll change the label system given how complicated it would be. Any change would involve tradeoffs. I thought I would mention this anyway.

**Comment by jbphet** [comment]
Both of the things noted above are by design, and I recall discussing them and implementing this behavior.  I'm going to unassign myself - @amanda-phet - please review and let me know if you think any changes are needed.  If not, you are free to close.

**Comment by amanda-phet** [comment]
Yes this is by design. There isn't a perfect solution to labels that are close, and the top most object will the one in focus (so, if you click the bird it will be layered above the text for the girl).
