### ISSUE TITLE
Thermometer icon has an odd white box when pressed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#75]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/465
On the first screen, you can choose between three different scenes using icon buttons. When you press down on them, they grey out. However, when pressing down on the thermometer icon there seems to be a weird white box in the image that isn't otherwise visible. Feel free to close if this is not a concern.

**Visuals**
![boxmometer](https://user-images.githubusercontent.com/41024075/72023896-445db680-3231-11ea-8ed8-aef0f64d1a33.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-rc.1/phet/number-line-integers_en_phet.html
Version: 1.0.0-rc.1 2020-01-06 19:43:39 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by amanda-phet** [comment]
@jbphet I'm guessing you're using a thermometer image there with a white background instead of transparent. I can see it before it is even pressed. Where did you get the image?

**Comment by jbphet** [comment]
> Where did you get the image?

It's programmatically generated, and I had enclosed the thermometer in a white box in order to make its size consistent with the other icons.  I've changed that box's fill to transparent, and all is well.

**Comment by KatieWoe** [comment]
This seems fixed in rc.2
