### ISSUE TITLE
rtl shifts the numberline when thermometer are put on/taken off map

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#78]
**Device**
Bates
**OS**
Win 7
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/QA/issues/465. Only really seen with rtl so far. Occurs on any platform, but firefox seems most dramatic.
When adding the first or taking away the last thermometer on the climate scene of the first screen the number line to the left will change size and shift around. This can be quite noticeable on some platforms, such as firefox.

**Visuals**
![shiftingrtl](https://user-images.githubusercontent.com/41024075/72173953-de3e7400-3395-11ea-8725-78856249bd62.gif)

**Comment by loganbraywork** [comment]
On Windows 7 Chrome this occurs even without a stringTest

**Comment by jbphet** [comment]
This should be fixed now through the addition of max width values for the labels on the number line.

**Comment by loganbraywork** [comment]
Appears fixed as of latest RC test
