### ISSUE TITLE
Object doesn't support find

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#79]
**Test device**
Bates

**Operating System**
Win 7 or 10

**Browser**
IE

**Problem description**
For https://github.com/phetsims/QA/issues/465.
Trying to use the buttons to add/take away money from the piggy banks will freeze the sim. First, it will pause for a long time, jump to a new position, and then completely freeze. Console errors shown in the video.

**Visuals**
![propertymethodfind](https://user-images.githubusercontent.com/41024075/72180883-60826480-33a5-11ea-87d1-99a281fb66fd.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
  
Name: ‪Number Line: Integers‬

URL: https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-rc.1/phet/number-line-integers_en_phet.html

Version: 1.0.0-rc.1 2020-01-06 19:43:39 UTC

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled, pixelRatioScaling

User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0; rv:11.0) like Gecko

Language: en-US

Window: 1536x750

Pixel Ratio: 2.5/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
I think it is due to this commit: https://github.com/phetsims/number-line-integers/commit/4e41c6eb52456a7a085de6c9574fb23f35c6a41f

**Comment by jbphet** [comment]
Change looks good to me, thanks @SaurabhTotey.

**Comment by jbphet** [comment]
I've propagated the commit to the 1.0 release branch, marking as fixed.

**Comment by KatieWoe** [comment]
Seems fixed in rc.2
