### ISSUE TITLE
Layering of elevation screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#83]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/466.
On the elevation scene I noticed that the person/fish/bird are layered behind the number line. This looks a bit odd to me.

**Visuals**
![behindtheline](https://user-images.githubusercontent.com/41024075/72853539-ed170780-3c6e-11ea-905f-670fafa9e7ff.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-rc.2/phet/number-line-integers_en_phet.html
Version: 1.0.0-rc.2 2020-01-21 16:03:10 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
This doesn't seem like a bug, but I'm fine if we change the layering in this case (the thermometer goes over the number line, so it would be consistent with that screen). 

Let's wait and see if there's anything else @jbphet has to fix, but this alone doesn't warrant another RC in my opinion.

**Comment by KatieWoe** [comment]
This is done, but may be related to https://github.com/phetsims/number-line-integers/issues/88
