### ISSUE TITLE
Hitting reset / reset all button while dragging items can leave items in play area

### ISSUE THREAD

**Issue by ghost** [phetsims/number-line-integers#84]
**Test Device**

MacBook Air

**Operating System**

macOS 10.15.2

**Browser**

Chrome 79.0.3945.117

**Problem Description**

For https://github.com/phetsims/QA/issues/466. Might be a common code issue. Problem seems similar to https://github.com/phetsims/isotopes-and-atomic-mass/issues/42.

If you hit the reset all button while dragging an item such as PhET Girl, the penguin, the fish, a thermometer, etc. then hit the reset button or the reset all button, your item will still be in the play area.

**Visuals**

![issue](https://user-images.githubusercontent.com/31285590/72853854-cdccaa00-3c6f-11ea-92f3-c9042d782419.gif)

The case of the thermometer is especially strange because after the reset all button is pressed, the thermometer goes back to its original toolbox size but retains its position.

<details>
<summary><b>Troubleshooting information</b></summary>
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-rc.2/phet/number-line-integers_en_phet.html
Version: 1.0.0-rc.2 2020-01-21 16:03:10 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
Language: en-US
Window: 1440x821
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by KatieWoe** [comment]
This seems fixed in rc 3
