### ISSUE TITLE
C and F have different comparison boxes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#85]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/466.
On the temperature scene, the comparison statement boxes for Fahrenheit and Celsius are separate. If you collapse one, then switch to the other view, the box will be collapsed (if that was the state that temperature was in). Switching back will reveal the collapsed box again. They are also unaffected by resetting the scene, though the temperature setting does change back to Fahrenheit.
**Steps to reproduce**
1. Go to the temperature scene on a fresh load
2. Collapse the comparison statement box
3. Switch to Celsius
4. Observe box

**Visuals**
![cfcomparison](https://user-images.githubusercontent.com/41024075/72917575-521b3d80-3d01-11ea-916b-f858bec6f814.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-rc.2/phet/number-line-integers_en_phet.html
Version: 1.0.0-rc.2 2020-01-21 16:03:10 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment]
Just to be clear, it doesn't matter that they have separate comparison boxes, what matters is that the open state of the two boxes can get out of sync with one another.

**Comment by KatieWoe** [comment]
Which direction of comparison is also impacted

**Comment by KatieWoe** [comment]
Seems fixed in rc.3, but may be related to https://github.com/phetsims/number-line-integers/issues/87
