### ISSUE TITLE
Comparison arrows on Explore screen do not reset with reset all

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#87]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/468. This did not occur in rc 2.
If you change the direction of the comparison statement on the explore screen (greater than instead of less than) and hit the orange reset all button, this setting does not reset. This bug does not occur in rc 2 or on the Generic screen.

**Visuals**
![resetallarrow](https://user-images.githubusercontent.com/41024075/73085471-fb8e3a80-3e8b-11ea-9382-71a77b0adb6e.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-rc.3/phet/number-line-integers_en_phet.html
Version: 1.0.0-rc.3 2020-01-24 00:21:22 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
May be related to https://github.com/phetsims/number-line-integers/issues/85

**Comment by loganbraywork** [comment]
The arrows do reset on IPad OS 13 for some reason even though this bug consistently shows up on Mac and Windows

**Comment by loganbraywork** [comment]
Seems to be fixed
