### ISSUE TITLE
Temperature scene: reset scene resets Labels and Absolute Value, but not checkboxes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#89]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/468. Does seem to happen in rc 2. Only seems to happen on temperature scene.
When hitting the grey reset scene button, the expected behavior is for the checkboxes on the right to not be reset. This behavior seems to work on the elevation and piggy bank scene. However, in the temperature scene, while the checkboxes appear to retain their setting, the behavior of Labels and Absolute Value does reset.
**Steps to reproduce**
1. Go to the temperature scene
2. Uncheck Labels and check Absolute Values
3. Observe behavior with a thermometer in the play area
4. Hit the grey reset scene button
5. Observe boxes
6. Drag a thermometer out
7. Observe sim behavior

**Visuals**
![resetscenetemp](https://user-images.githubusercontent.com/41024075/73090946-9c81f300-3e96-11ea-8111-8e2f6d0754a1.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-rc.3/phet/number-line-integers_en_phet.html
Version: 1.0.0-rc.3 2020-01-24 00:21:22 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
It seems to be centered on the number line. The label in the play area that goes with absolute value is still there, but the line to zero on the number line isn't.

**Comment by jbphet** [comment]
Turns out the number line was getting a full reset on a scene reset.  I changed the code to remove all points but not do a full reset in this case.

**Comment by KatieWoe** [comment]
Looks good in rc4
