### ISSUE TITLE
Include attribution for temperature data

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-integers#9]
@kathy-phet and @amanda-phet showed me the site https://cds.climate.copernicus.eu/cdsapp#!/home as a possible source for the temperature data needed in the "Temperature" scene.  This seems to be working out well, but this morning as I was using it, a dialog popped up about accepting the license.  I skimmed through it, and I think we could probably meet the terms of it by mentioning them in the "Thanks" section of the credits, but I know very little about licensing laws, so thought it best to be safe.

I've attached the license file, and it's pretty short.  Can we have someone look it over and decide first whether we can use the data from the site as the basis for our temperature map and second how we need to attribute it to them?
[20180314_Copernicus_License_V1.1.pdf](https://github.com/phetsims/number-line-integers/files/3387286/20180314_Copernicus_License_V1.1.pdf)

**Comment by jbphet** [comment]
Assigning @ariel-phet for now.

**Comment by amanda-phet** [comment]
@kathy-phet and I reviewed the license and we will plan to include this attribution: Generated using Copernicus Climate Change Service information (2019) 

I am not positive where it should go- Kathy or Ariel should know.

**Comment by ariel-phet** [comment]
@amanda-phet I would follow what you did in Least Squares Regression where you have an "info" button, that seems reasonable and sufficient.

**Comment by amanda-phet** [comment]
The info button seems really heavy-handed for this sim.. in LSR the info button shared different information depending on the data set being viewed. Do we need to attribution right on the sim? Or can it go in the code and teacher tips instead? 

If it needs to be on the sim, maybe we can include small text right under the map itself?

**Comment by ariel-phet** [comment]
Small text right in the sim seems totally reasonable to me (we have something similar in gene expression)

**Comment by amanda-phet** [comment]
I realized we might also want a sentence describing the data (a student in an interview even asked me which day we were looking at during that month!). 

One idea is to put this information right under the map:
![image](https://user-images.githubusercontent.com/7852916/66774956-237b0480-ee80-11e9-9d40-40b6fa4eb380.png)

Alternatively, we can nest the information in an info button:
![image](https://user-images.githubusercontent.com/7852916/66774978-3261b700-ee80-11e9-88a7-4993eb9dd3d5.png)
![image](https://user-images.githubusercontent.com/7852916/66774991-3d1c4c00-ee80-11e9-9837-d7e0791dbf68.png)

**Comment by kathy-phet** [comment]
Do you have a preference? If it is under the graph, I think it can be another pixel or two smaller font.

**Comment by amanda-phet** [comment]
I think I prefer the persistent one so there isn't another button. I agree a smaller font could be fine too. 

I would love to know if others have preferences too!

**Comment by jbphet** [comment]
I too would express a preference for the persistent one under the graph.  Shall I move forward with the implementation?

**Comment by jbphet** [comment]
Discussed during fire alarm, consensus is to add it but in a fairly small font (probably 10 pt) and use a gray rather than black color.

**Comment by jbphet** [comment]
This is in place on master.  I showed it to @amanda-phet and @kathy-phet, and they generally agreed that it looked good, but @amanda-phet wanted to check the contrast using some tools that she has.  Assigning to her for that, she can close if it looks good or assign back to me if it needs some changes.

**Comment by amanda-phet** [comment]
It looks like you're using #999999 and that indeed fails WCAG guidelines. Please change it to #707070 for a higher contrast (still gray, but darker).

**Comment by jbphet** [comment]
Update made.  Are we good to go on this now @amanda-phet?

**Comment by amanda-phet** [comment]
Looks good, thanks.

**Comment by ghost** [comment]
@jbphet and I were wondering if the "2m" in
![Screen Shot 2020-01-21 at 4 15 08 PM](https://user-images.githubusercontent.com/31285590/72851566-39f7df80-3c69-11ea-9c19-4da0e01e3e3e.png)
is, from a middle school student's perspective, too vague.

Should it be changed to "Two-Meter"? Thoughts? @amanda-phet, @ariel-phet

N.B. "2m" seems to be standard climatology phraseology.

Linking to https://github.com/phetsims/QA/issues/466.

**Comment by amanda-phet** [comment]
@kathy-phet ? 

I am not too concerned with folks interpreting this attribution, so I can go either way.

**Comment by ariel-phet** [comment]
@amanda-phet @jbphet @lmulhall-phet 

I agree with @lmulhall-phet that 2m is a bit vague for most people. I also agree with @amanda-phet that we should not be too concerned about this attribution. However, since it is always visible, why not a compromise that is more interpret-able and basically accurate. Why don't we tweak the phrase slightly:

> 2018 Monthly Averaged Surface Air Temperature

It is true that it is the temperature 2 m above the surface, but I think Surface Air temperature gets that idea - it is the temperature of air near the surface, and then we are not using climate jargon, and it is likely not going to make students ask the question "what is 2m?"

**Comment by KatieWoe** [comment]
This change is implemented in rc.3
