### ISSUE TITLE
Long absolute value labels can go off screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#90]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firfox
**Problem description**
For https://github.com/phetsims/QA/issues/468. Minor issue in my opinion.
The absolute value labels on the elevation and thermometer scenes can go off the screen if strings are long.
**Steps to reproduce**
1. Use double string test and show dev bounds (this show layout for small windows/iPads/etc.)
2. Turn on absolute value on elevation or thermometer scene
3. Drag an object to the right edge of the play area while still being in that area

**Visuals**
![outofbounds](https://user-images.githubusercontent.com/41024075/73101039-140e4d00-3eac-11ea-9283-4cd4c5e1b3ec.png)
![outofbounds2](https://user-images.githubusercontent.com/41024075/73101040-140e4d00-3eac-11ea-8a2d-daf620a23df9.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬:‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-rc.3/phet/number-line-integers_en_phet.html?stringTest=double&dev
Version: 1.0.0-rc.3 2020-01-24 00:21:22 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
Since the user can technically drag the object to the left to read the statement (in the elevation scene), I'm not too concerned about this. The temperature scene is fairly minor, otherwise I might try to think of a way to fix this. 

Thanks for finding this @KatieWoe .
