### ISSUE TITLE
put listbox above range combo box?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-integers#93]
In the lower-right corner of the _Generic_ screen, there's a ComboBox. It looks like this when the comb box's listbox is closed:

<img width="951" alt="screenshot_72" src="https://user-images.githubusercontent.com/3046552/73381835-ab481b80-4283-11ea-9125-9ef6e65f6234.png">

When the listbox opens, it opens _below_ the combo box button, covering the scene selection buttons.  It will also be below the finger of touch users, possible obscuring the listbox.

<img width="949" alt="screenshot_73" src="https://user-images.githubusercontent.com/3046552/73381844-aedba280-4283-11ea-80bb-6a3ebb1d8144.png">

This seems like an excellent place to use the `listPosition: 'above'` feature of ComboBox.  This would make the listbox appear _above_ the combo box's button, and above the touch user's finger.  It looks like this:

<img width="923" alt="screenshot_74" src="https://user-images.githubusercontent.com/3046552/73382072-1eea2880-4284-11ea-8af5-07fbf018b37f.png">

This involves adding 1 line to the instantiation of `rangeSelectionComboBox` in NLIGenericScreenView.js:

`listPosition: 'above',`

**Comment by amanda-phet** [comment]
@pixelzoom it's funny you bring this up because the original mockups had that pointing upward, but I assumed the decision was based on whether there was room or not for the box to expand. I'd be happy to switch the direction for this sim and continue it in the other two.

**Comment by jbphet** [comment]
Thanks @pixelzoom - good suggestions.

@amanda-phet - I have implemented this change.  Please check it out on master and make sure you're good with it.  Assuming you are, please assign it back to me and I'll do a maintenance release.  I figure we would need to do this before publishing the other Number Line sims anyway just to keep things consistent, so I might as well just do it now and let users start getting used to it.

**Comment by amanda-phet** [comment]
Looks good to me!

**Comment by jbphet** [comment]
I've done the maintenance release, this change is in place as of version 1.0.1.  Closing.
