### ISSUE TITLE
ElevationPointController calls NumberLinePoint with incorrect argument types

### ISSUE THREAD

**Issue by samreid** [phetsims/number-line-integers#98]
From https://github.com/phetsims/tasks/issues/1035, 

> Number Line Suite: Cannot read property 'valueToModelPosition' of undefined

It looks like ElevationPointController is calling:
```js
const numberLinePoint = new NumberLinePoint( numberLine, {
```

But NumberLinePoint signature is :

```js
  /**
   * {number} initialValue - the value on the number line
   * {Color} color - the color that should be used to portray this point in the view
   * {NumberLine} numberLine - the number line on which this point exists
   * {PointController} [controller] - the controller that will move this point
   * @public
   */
  constructor( initialValue, color, numberLine, controller = null ) {
```

@jbphet can you please take a look?

**Comment by jbphet** [comment]
I think this may have been the result of a commit that failed to push.  I was able to run fuzz test successfully on my own machine, so I checked to see if there were any pending commits and there weren't, but there was a pending push, so I just pushed it.  I'll check back in an hour or two and see whether automated testing is succeeding.

**Comment by jbphet** [comment]
This is fixed.  Another, different error popped up too related to a recent refactor (as this one was), but that too should now be fixed.  Closing.
